name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20.17
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub 
        uses: docker/login-action@v2 
        with: 
         username: ${{ secrets.DOCKERHUB_USERNAME }} 
         password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Build and push Docker image 
        run: | 
         cd Cafe_Management_System
         cd api-gateway
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway . 
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway
         cd ../customer-services
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/customer-services . 
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/customer-services
         cd ../inventory-services
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/inventory-services . 
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/inventory-services
         cd ../menu-services
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/menu-services . 
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/menu-services
         cd ../order-services
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/order-services . 
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/order-services
         cd ../payment-services
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/payment-services . 
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/payment-services
