name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20.17
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - name: Log in to Docker Hub 
        uses: docker/login-action@v2 
        with: 
         username: ${{ secrets.DOCKERHUB_USERNAME }} 
         password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Build and push Docker image 
        run: | 
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-express-app:latest . 
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-express-app:latest

  cleanDocker: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Clean up old Docker containers 
      uses: appleboy/ssh-action@v0.1.1 
      with: 
       host: ${{ secrets.HOST_IP }} 
       username: ${{ secrets.SSH_USERNAME }} 
       key: ${{ secrets.HOST_SSH_PRIVATE_KEY }} 
       script: | 
        docker stop my-express-app || true 
        docker rm my-express-app || true
